### ISSUE TITLE
【建议】可以添加邮箱通知的功能吗？

### ISSUE THREAD

**Issue by HorrZzz** [kngkngtian/AutoReport#1]
【建议】可以添加邮箱通知的功能吗？

**Comment by tienskowl** [comment]
现在是使用方糖的API直接推送到微信，我感觉这个方式提醒功能更强而且只需要GitHub账号就可以使用。如果强烈需求的话可以等我放寒假了加上这个功能。

**Comment by HorrZzz** [comment]
谢谢大佬！

**Comment by tienskowl** [comment]
切换到email分支，下载代码包部署一下试试
