### ISSUE TITLE
好像不能用了

### ISSUE THREAD

**Issue by Guolipeng666** [kngkngtian/AutoReport#2]
好像不能用了，云函数测试失败，返回结果是
{

  "errorCode": 1,

  "errorMessage": "user code exception caught",

  "stackTrace": "Error: Cannot find module 'axios'\nRequire stack:\n- /var/user/index.js\n- /var/runtime/node12/UserFunction.js\n- /var/runtime/node12/Runtime.engine.js\n- /var/runtime/node12/bootstrap.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:864:27)\n    at Module.require (internal/modules/cjs/loader.js:1044:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Runtime.exports.main_handler [as handler] (/var/user/index.js:3:17)\n    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)\n    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)",

  "statusCode": 430

}****

**Comment by tienskowl** [comment]
你是第一次部署吗，如果是第一次的话需要选择在线安装依赖

**Comment by tienskowl** [comment]
![QQ截图20210102225133](https://user-images.githubusercontent.com/28488890/103459921-4deb0300-4d4d-11eb-9efb-1c65c3706ca2.png)

**Comment by Guolipeng666** [comment]
你好，我是第一次部署，问题应该是出在了安装依赖那里，我的页面里面没有在线安装依赖&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "康康"; 
Date: 2021年1月2日(星期六) 晚上10:49
To: "kngkngtian/AutoReport"; 
Cc: "Guolipeng666"<1707040113@s.upc.edu.cn>; "Author"; 
Subject: Re: [kngkngtian/AutoReport] 好像不能用了 (#2)

&nbsp;


 
你是第一次部署吗，需要选择在线安装依赖

**Comment by Guolipeng666** [comment]
我找到了新版本的安装依赖位置，已经成功了，谢了&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "康康"; 
Date: 2021年1月2日(星期六) 晚上10:49
To: "kngkngtian/AutoReport"; 
Cc: "Guolipeng666"<1707040113@s.upc.edu.cn>; "Author"; 
Subject: Re: [kngkngtian/AutoReport] 好像不能用了 (#2)

&nbsp;


 
你是第一次部署吗，需要选择在线安装依赖
