### ISSUE TITLE
可耻的伸手

### ISSUE THREAD

**Issue by deepdarkfantacy311** [kngkngtian/AutoReport#4]
大佬，怎么用chrome获取form data啊

**Comment by tienskowl** [comment]
阿这，readme里边已经写得很清楚了啊

**Comment by deepdarkfantacy311** [comment]
我只有chrome，没有chromium，无法按步骤来



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "康康"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上10:31
收件人: "kngkngtian/AutoReport"<AutoReport@noreply.github.com&gt;; 
抄送: "鹅城牧之"<3539840862@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kngkngtian/AutoReport] 可耻的伸手 (#4)





 
阿这，readme里边已经写得很清楚了啊

**Comment by tienskowl** [comment]
Chrome就是基于chromium的，操作一致

**Comment by deepdarkfantacy311** [comment]
能不能把你疫情防控通页面的form data复制給我呢，我可以比对一下，可能我版本太低了，很多按钮找不到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "康康"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上10:39
收件人: "kngkngtian/AutoReport"<AutoReport@noreply.github.com&gt;; 
抄送: "鹅城牧之"<3539840862@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kngkngtian/AutoReport] 可耻的伸手 (#4)





 
Chrome就是基于chromium的，操作一致

**Comment by tienskowl** [comment]
formdata里有个人信息，大概就长这个样子
![QQ截图20210112232248](https://user-images.githubusercontent.com/28488890/104334449-57365580-552d-11eb-96b4-e31f13f97070.png)

**Comment by tienskowl** [comment]
只要不是太远古的chrome都是可以的，如果你遇到问题了，可以指出是在哪一个步骤出了问题

**Comment by deepdarkfantacy311** [comment]
![image](https://user-images.githubusercontent.com/77332579/104335122-125eee80-552e-11eb-8f10-b15c0b9de419.png)
怎么在这图里找form data，或者在哪输入vm.save()

**Comment by huaidan233** [comment]
> ![image](https://user-images.githubusercontent.com/77332579/104335122-125eee80-552e-11eb-8f10-b15c0b9de419.png)
> 怎么在这图里找form data，或者在哪输入vm.save()

console里输入vm.save()就可以了

**Comment by huaidan233** [comment]
难不成这就是UPC的懒狗聚集地嘛【doge】满脑子自动化

**Comment by deepdarkfantacy311** [comment]
但是network里找不到save

**Comment by deepdarkfantacy311** [comment]
> 难不成这就是UPC的懒狗聚集地嘛【doge】满脑子自动化

懒是进步的动力（逃

**Comment by tienskowl** [comment]
console里输入 `vm.save()`，然后去network里就有`save`项了

**Comment by huaidan233** [comment]
> 但是network里找不到save

找找就可以了，输入之后那个network里就会出现

**Comment by tienskowl** [comment]
或者输入`vm.save()`之前先清空network里边的内容，点击左上角的红色圆圈左边的禁止符号

**Comment by huaidan233** [comment]
你们说会不会有根据这个js做生意的人

**Comment by tienskowl** [comment]
10元代签

**Comment by huaidan233** [comment]
> 10元代签

大佬何不闭源然后拿出来做生意

**Comment by tienskowl** [comment]
开源多好，方便大家

**Comment by huaidan233** [comment]
> 开源多好，方便大家

光这配置估计就得劝退所有非计科类的学生

**Comment by huaidan233** [comment]
也好，小范围使用，省的被封或者学校改方案

**Comment by deepdarkfantacy311** [comment]
点view source后那一堆乱码就是form data，还是带有汉字个人信息的？

**Comment by huaidan233** [comment]
> 点view source后那一堆乱码就是form data，还是带有汉字个人信息的？

乱码

**Comment by deepdarkfantacy311** [comment]
本数学懒狗在此谢过大佬们（逃

**Comment by huaidan233** [comment]
> 本数学懒狗在此谢过大佬们（逃

带一？

**Comment by deepdarkfantacy311** [comment]
是这样的（逃

**Comment by huaidan233** [comment]
> 是这样的（逃

加个好友🐎？

**Comment by deepdarkfantacy311** [comment]
你也是新生？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huaidan233"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上11:53
收件人: "kngkngtian/AutoReport"<AutoReport@noreply.github.com&gt;; 
抄送: "鹅城牧之"<3539840862@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kngkngtian/AutoReport] 可耻的伸手 (#4)





  
是这样的（逃
  
加个好友🐎？

**Comment by deepdarkfantacy311** [comment]
👴的丘丘：3539840862

**Comment by huaidan233** [comment]
> 你也是新生？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "huaidan233"<notifications@github.com&gt;; 发送时间: 2021年1月12日(星期二) 晚上11:53 收件人: "kngkngtian/AutoReport"<AutoReport@noreply.github.com&gt;; 抄送: "鹅城牧之"<3539840862@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [kngkngtian/AutoReport] 可耻的伸手 (#4) 是这样的（逃 加个好友🐎？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

地信带一

**Comment by huaidan233** [comment]
> 3539840862

1550674842你的好像加8上

**Comment by deepdarkfantacy311** [comment]
> > 你也是新生？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "huaidan233"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2021年1月12日(星期二) 晚上11:53 收件人: "kngkngtian/AutoReport"<[AutoReport@noreply.github.com](mailto:AutoReport@noreply.github.com)>; 抄送: "鹅城牧之"<[3539840862@qq.com](mailto:3539840862@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [kngkngtian/AutoReport] 可耻的伸手 (#4) 是这样的（逃 加个好友🐎？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 地信带一

都是被防控逼到这的鼠鼠（逃

**Comment by huaidan233** [comment]
> > > 你也是新生？
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "huaidan233"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2021年1月12日(星期二) 晚上11:53 收件人: "kngkngtian/AutoReport"<[AutoReport@noreply.github.com](mailto:AutoReport@noreply.github.com)>; 抄送: "鹅城牧之"<[3539840862@qq.com](mailto:3539840862@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [kngkngtian/AutoReport] 可耻的伸手 (#4) 是这样的（逃 加个好友🐎？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 地信带一
> 
> 都是被防控逼到这的鼠鼠（逃

都是懒狗

**Comment by leyouBaloy** [comment]
大佬，加个qq好友吗?

**Comment by tienskowl** [comment]
> 大佬，加个qq好友吗?

不了吧，老社恐了
