### ISSUE TITLE
有几个问题。

### ISSUE THREAD

**Issue by leyouBaloy** [kngkngtian/AutoReport#5]
新版本的位置是如何确定的？

**Comment by tienskowl** [comment]
系统是在本地通过对比你两次位置信息是否一致确定你是否移动的，为了实现这个功能，它的接口中返回了你昨天填写的数据，修改日期之后提交即可

**Comment by leyouBaloy** [comment]
非常nice，感谢作者。

**Comment by leyouBaloy** [comment]
还有一个问题请教，请问可以把上传到腾讯云函数的教程写详细一些吗，我没有学过js，自己尝试上传了一下，没有成功

**Comment by tienskowl** [comment]
> 还有一个问题请教，请问可以把上传到腾讯云函数的教程写详细一些吗，我没有学过js，自己尝试上传了一下，没有成功

哪一步出了问题

**Comment by leyouBaloy** [comment]
我进行了测试，测试失败
返回结果：{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Error: Cannot find module 'axios'\nRequire stack:\n- /var/user/index.js\n- /var/runtime/node12/UserFunction.js\n- /var/runtime/node12/Runtime.engine.js\n- /var/runtime/node12/bootstrap.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:864:27)\n    at Module.require (internal/modules/cjs/loader.js:1044:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Runtime.exports.main_handler [as handler] (/var/user/index.js:3:17)\n    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)\n    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)","statusCode":430}

**Comment by tienskowl** [comment]
> 我进行了测试，测试失败
> 返回结果：{"errorCode":-1,"errorMessage":"user code exception caught","stackTrace":"Error: Cannot find module 'axios'\nRequire stack:\n- /var/user/index.js\n- /var/runtime/node12/UserFunction.js\n- /var/runtime/node12/Runtime.engine.js\n- /var/runtime/node12/bootstrap.js\n at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)\n at Function.Module._load (internal/modules/cjs/loader.js:864:27)\n at Module.require (internal/modules/cjs/loader.js:1044:19)\n at require (internal/modules/cjs/helpers.js:77:18)\n at Runtime.exports.main_handler [as handler] (/var/user/index.js:3:17)\n at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)\n at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)\n at listOnTimeout (internal/timers.js:549:17)\n at processTimers (internal/timers.js:492:7)","statusCode":430}

进入代码编辑页面，编辑框下方有个`在线安装依赖`，打开

**Comment by leyouBaloy** [comment]
![QQ截图20210116181146](https://user-images.githubusercontent.com/71641224/104809208-84814d00-5826-11eb-91ca-d1c52c3b50e6.jpg)

**Comment by tienskowl** [comment]
打开之后部署一下，看看有没有生成`node_modules`文件夹

**Comment by Veagau** [comment]
新版云函数更新后，好像dayjs也要加到packet.json里面，要不然自动安装依赖还是会报错

**Comment by Veagau** [comment]
> 新版云函数更新后，好像dayjs也要加到package.json里面，要不然自动安装依赖还是会报错

在函数代码页打开`package.json`将依赖改成如下，然后再安装一下依赖→部署→测试就可以了：
```
{
  "dependencies": {
    "axios": "^0.21.1",
    "dayjs":"^1.8.24"
  }
}
```

**Comment by tienskowl** [comment]
> > 新版云函数更新后，好像dayjs也要加到package.json里面，要不然自动安装依赖还是会报错
> 
> 在函数代码页打开`package.json`将依赖改成如下，然后再安装一下依赖→部署→测试就可以了：
> 
> ```
> {
>   "dependencies": {
>     "axios": "^0.21.1",
>     "dayjs":"^1.8.24"
>   }
> }
> ```

改代码的时候忘记修改package.json了，哈哈😂

**Comment by leyouBaloy** [comment]
太棒啦，测试成功。
关于定位问题，上传到云函数之后定位肯定不正确，“系统是在本地通过对比你两次位置信息是否一致确定你是否移动的，为了实现这个功能，它的接口中返回了你昨天填写的数据，修改日期之后提交即可”，这句话的意思是不是这个程序可以自动检测昨天的位置填入，就不用人再去操心了？

**Comment by tienskowl** [comment]
> 太棒啦，测试成功。
> 关于定位问题，上传到云函数之后定位肯定不正确，“系统是在本地通过对比你两次位置信息是否一致确定你是否移动的，为了实现这个功能，它的接口中返回了你昨天填写的数据，修改日期之后提交即可”，这句话的意思是不是这个程序可以自动检测昨天的位置填入，就不用人再去操心了？

对，如果你需要修改信息的话，在你设置的触发器触发之前手动填表提交一次即可。具体数据可以登录疫情防控通网站，打开控制台，输入`document.querySelector("body > script:nth-child(6)")`即可看到。

**Comment by leyouBaloy** [comment]
perfect!
