### ISSUE TITLE
关于Server酱通知的使用

### ISSUE THREAD

**Issue by Veagau** [kngkngtian/AutoReport#6]
我发现那个七点通知好像没有生效，因此我把那个If 条件判断给注释掉了，把PostInfo改成如下形式，点击测试之后微信端成功接收到了通知
```
  // 推送消息
  const postInfo = async () => {
    return await axios({
      method: 'post',
      url: encodeURI(`https://sc.ftqq.com/${apiKey}.send?text=${text}`),
    }).catch((err) => console.log(err))
  }
```

**Comment by tienskowl** [comment]
我测试了一下，正常运行。如果你是在测试的时候发现的，那可能是触发了Server酱的重复消息限制；如果不是的话我还真不知道咋回事了

**Comment by Veagau** [comment]
> 我测试了一下，正常运行。如果你是在测试的时候发现的，那可能是触发了Server酱的重复消息限制；如果不是的话我还真不知道咋回事了

昨晚部署之后，今天早上七点没有收到通知，注释掉IF之后，点击测试可以正确Get到微信通知

**Comment by Veagau** [comment]
> 我测试了一下，正常运行。如果你是在测试的时候发现的，那可能是触发了Server酱的重复消息限制；如果不是的话我还真不知道咋回事了

昨晚部署之后，今天早上七点没有收到通知，注释掉IF之后，点击测试可以正确Get到微信通知。不过其实也没有太大影响，只是通知时间的问题，比较习惯填好就通知，这样就不用等明早七点的微信消息了

**Comment by tienskowl** [comment]
根据自己需求配置一下，我是按照我自己的需求写的😁
