### ISSUE TITLE
带佬你康康我这个错是哪里出问题了？

### ISSUE THREAD

**Issue by peaky2222** [kngkngtian/AutoReport#7]
![image](https://user-images.githubusercontent.com/47955707/106095757-4b72a200-616f-11eb-8413-560b8d7d9aa6.png)

俺规范步骤试了好几次了，一直是这个错误。

谢谢

**Comment by tienskowl** [comment]
账号密码确定填对了吗

**Comment by peaky2222** [comment]
确定的，因为https://app.upc.edu.cn/uc/wap/login，这个是可以登录的，密码也是数字石大的密码，但是还是这个问题，大佬看看还有没有可能其他情况？

**Comment by peaky2222** [comment]
![image](https://user-images.githubusercontent.com/47955707/106231977-e7fb7980-622d-11eb-8306-78cb6a31952b.png)
带佬，破案了，密码的最后一位or密码内不能有字符 ‘+’，我之前一直存在问题，但是用带+的密码是可以登录数字石大的，但是用这个函数的时候会失败，带佬有精力的话可以复现下错误，将密码的最后一位改为‘+’，查明一下到底问题出在哪里！谢谢，总之能用了！！！谢谢谢

**Comment by HorrZzz** [comment]
我字母➕数字的密码组合，也出现了该error
