### ISSUE TITLE
不同账号，同密码，其中一个号出现了error

### ISSUE THREAD

**Issue by HorrZzz** [kngkngtian/AutoReport#8]
同一个函数服务下，两个号密码相同，学号不同，结果其中一个号测试的时候会出现error，另一个号一切正常，依赖也没问题

返回结果
{
  "errorCode": -1,
  "errorMessage": "user code exception caught",
  "stackTrace": "TypeError: Cannot create property 'date' on boolean 'false'\n    at getData (/var/user/index.js:47:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Runtime.exports.main_handler [as handler] (/var/user/index.js:83:16)",
  "statusCode": 430
}

**Comment by tienskowl** [comment]
不如你改个密码试试？最近在准备面试没有时间更新这个🥴

**Comment by HorrZzz** [comment]
嗯嗯，不着急，祝顺利

PS: 这还有另一个error

TypeError: Cannot create property 'date' on boolean 'false'
    at getData (/var/user/index.js:47:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runtime.exports.main_handler [as handler] (/var/user/index.js:83:16)
