### ISSUE TITLE
找不到axios模块

### ISSUE THREAD

**Issue by HenryFang123** [kngkngtian/AutoReport#9]
{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"c3af4e09-b477-40f1-845f-0b80ab4787b0","stackTrace":"Error: Cannot find module 'axios'\nRequire stack:\n- /var/user/index.js\n- /var/runtime/node12/UserFunction.js\n- /var/runtime/node12/Runtime.engine.js\n- /var/runtime/node12/bootstrap.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:864:27)\n    at Module.require (internal/modules/cjs/loader.js:1044:19)\n    at require (internal/modules/cjs/helpers.js:77:18)\n    at Runtime.exports.main_handler [as handler] (/var/user/index.js:3:17)\n    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)\n    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)\n    at listOnTimeout (internal/timers.js:549:17)\n    at processTimers (internal/timers.js:492:7)","statusCode":430}

**Comment by HenryFang123** [comment]
1

**Comment by tienskowl** [comment]
解决了？

**Comment by HenryFang123** [comment]
是的，是部署那里的问题，代码正常，不然module文件夹生成不出来


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 康康 ***@***.***&gt;
发送时间: 2021年4月3日 13:21
收件人: tienskowl/AutoReport ***@***.***&gt;
抄送: HenryFang123 ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[tienskowl/AutoReport] 找不到axios模块 (#9)





 
解决了？
